{{- if .Values.createAppSecret }}
# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}