{{- if .Values.createSecret }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "service.fullname" . }}
spec:
  provider: aws
  parameters:
    objects:  |
      {{- range .Values.SecretProviderClass.objects }}
      - objectName: {{ .objectName }}
        objectType: {{ .objectType }}
        objectAlias: {{ .objectAlias }}
        region: {{ .region }}
      {{- end }}
{{- end }}