{
 "title": "Jmx Dashboard(tomcat)",
 "description": "jmx exporter monitor",
 "tags": [ "jmx" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "APP_NAME",
    "query": {
     "query": "label_values(up{job=\"jmx-metrics\"},app_name)"
    }
   },
   {
    "name": "instance",
    "label": "POD_IP",
    "query": {
     "query": "label_values(up{job=\"jmx-metrics\", app_name=\"$app\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "java_lang_OperatingSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "up",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "java_lang_Runtime_Uptime",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"} / 1000"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "java_lang_Runtime_StartTime",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "stat",
   "description": "java_lang_OperatingSystem_OpenFileDescriptorCount",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"jmx-metrics\", instance=\"$instance\", app_name=\"$app\"}"
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "stat",
   "description": "java_lang_OperatingSystem_SystemCpuLoad",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "CPU Process Load(1m avg)",
   "type": "stat",
   "description": "java_lang_OperatingSystem_ProcessCpuLoad",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_ProcessCpuLoad{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[1m]) * 100"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "stat",
   "description": "java_lang_OperatingSystem_SystemLoadAverage",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage{job=\"jmx-metrics\", instance=\"$instance\", app_name=\"$app\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "java_lang_OperatingSystem_AvailableProcessors",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "java_lang_GarbageCollector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "GC count",
   "type": "timeseries",
   "description": "java_lang_GarbageCollector_CollectionCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(java_lang_GarbageCollector_CollectionCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "description": "java_lang_GarbageCollector_CollectionTime",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(java_lang_GarbageCollector_CollectionTime{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  { "title": "java_lang_MemoryPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Pool Used",
   "type": "timeseries",
   "description": "java_lang_MemoryPool_Usage_used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_used{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Memory Pool Committed",
   "type": "timeseries",
   "description": "java_lang_MemoryPool_Usage_committed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_Usage_committed{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  { "title": "java_lang_Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Heap /NonHeap Used",
   "type": "timeseries",
   "description": "java_lang_Memory_HeapMemoryUsage_used /  java_lang_Memory_NonHeapMemoryUsage_used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "HeapMemory"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"jmx-monitor\", teddy_app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "NonHeapMemory"
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap Committed",
   "type": "timeseries",
   "description": "java_lang_Memory_HeapMemoryUsage_committed /  java_lang_Memory_NonHeapMemoryUsage_committed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_committed{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "HeapMemory"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{job=\"jmx-monitor\", teddy_app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "NonHeapMemory"
    }
   ]
  },
  { "title": "java_lang_Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Threads Used",
   "type": "timeseries",
   "description": "java_lang_Threading_ThreadCount",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "java_lang_Threading_DaemonThreadCount{job=\"jmx-monitor\", teddy_app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  { "title": "java_lang_ClassLoading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Class Loaded / Unloaded",
   "type": "timeseries",
   "description": "java_lang_ClassLoading_LoadedClassCount / java_lang_ClassLoading_UnloadedClassCount",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "java_lang_ClassLoading_LoadedClassCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "java_lang_ClassLoading_UnloadedClassCount{job=\"jmx-monitor\", teddy_app=\"$app\", instance=\"$instance\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  { "title": "Catalina", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Catalina Request Processor bytes",
   "type": "timeseries",
   "description": "Catalina_GlobalRequestProcessor_bytesReceived /  Catalina_GlobalRequestProcessor_bytesSent",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_bytesReceived{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_bytesSent{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Catalina Request Processor requests",
   "type": "timeseries",
   "description": "Catalina_GlobalRequestProcessor_requestCount  /   Catalina_GlobalRequestProcessor_errorCount",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_requestCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{name}} count"
    },
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_errorCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{name}} error"
    }
   ]
  },
  {
   "title": "Catalina Request Processing Time",
   "type": "timeseries",
   "description": "Catalina_GlobalRequestProcessor_processingTime",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_processingTime{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval]) / increase(Catalina_GlobalRequestProcessor_requestCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina ThreadPool",
   "type": "timeseries",
   "description": "Catalina_readPool_connectionCount /  Catalina_ThreadPool_currentThreadsBusy  /  Catalina_ThreadPool_connectionCount   /   Catalina_ThreadPool_keepAliveCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "Catalina_ThreadPool_currentThreadCount{job=\"jmx-metrics\", instance=\"$instance\"}",
     "legendFormat": "current: {{name}}"
    },
    {
     "expr": "Catalina_ThreadPool_currentThreadsBusy{job=\"jmx-metrics\", instance=\"$instance\"}",
     "legendFormat": "current busy: {{name}}"
    },
    {
     "expr": "Catalina_ThreadPool_connectionCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "connection: {{name}}"
    },
    {
     "expr": "Catalina_ThreadPool_keepAliveCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "keepAlive: {{name}}"
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "timeseries",
   "description": "Catalina_ThreadPool_maxThreads",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "Catalina_ThreadPool_maxThreads{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Min Spare Threads",
   "type": "timeseries",
   "description": "Catalina_ThreadPool_minSpareThreads",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 61 },
   "targets": [
    {
     "expr": "Catalina_ThreadPool_minSpareThreads{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Accept Count",
   "type": "timeseries",
   "description": "Catalina_ThreadPool_acceptCount",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "Catalina_ThreadPool_acceptCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Poller Thread Count",
   "type": "timeseries",
   "description": "Catalina_ThreadPool_pollerThreadCount",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 65 },
   "targets": [
    {
     "expr": "Catalina_ThreadPool_pollerThreadCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}",
     "legendFormat": "name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "timeseries",
   "description": "Catalina_Servlet_requestCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "topk(5, increase(Catalina_Servlet_requestCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count",
   "type": "timeseries",
   "description": "Catalina_Servlet_errorCount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "topk(5, increase(Catalina_Servlet_errorCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "timeseries",
   "description": "Catalina_Servlet_processingTime  /  Catalina_Servlet_requestCount",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "topk(5, increase(Catalina_Servlet_processingTime{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])) / increase(Catalina_Servlet_requestCount{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
    }
   ]
  },
  {
   "title": "Catalina Manager Sessions",
   "type": "timeseries",
   "description": "Catalina_Manager_expiredSessions  /   Catalina_Manager_rejectedSessions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(increase(Catalina_Manager_expiredSessions{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(increase(Catalina_Manager_rejectedSessions{job=\"jmx-metrics\", app_name=\"$app\", instance=\"$instance\"}[$__rate_interval])) by (instance)",
     "legendFormat": "rejected"
    }
   ]
  }
 ]
}